remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Simple Page Template
description: Hello, world!
show_downloads: false
source: docs

# google_analytics: UA-XXXXXXXXX-1
